Squashed stripe 1st integration
Charge-Angels/ev-server pull request #2086
Opened 2021-02-08 14:35 UTC by ClaudeROSSI

Two endpoints have been added:
- one allowing the current user to link his card to his account (as a default payment method)
- one to trigger the invoice payment (using the the default payment method)

No unit tests so far ... existing billing tests are failing!

2021-02-08 14:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/LucasBrazi06/ev-server?pullRequest=2086) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/LucasBrazi06/ev-server?pullRequest=2086) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/LucasBrazi06/ev-server?pullRequest=2086) it.</sub>

2021-02-09 15:37 UTC, LucasBrazi06 requested changes
Use the new RESTful endpoint.

2021-02-09 15:37 UTC, LucasBrazi06 commented on src/server/rest/CentralRestServerService.ts
> +          [ServerAction.BILLING_ATTACH_PAYMENT_METHOD]: BillingService.handleBillingAttachPaymentMethod.bind(this),
You can also use the new RESTful API by adding BillingRouter.ts class in server/rest/v1/router/api
And declare the billing class in the GlobalRoute.ts
Check TenantRouter class, it should work the same.
So no need changes in that class anymore.

2021-02-09 15:37 UTC, LucasBrazi06 commented on src/integration/billing/stripe/StripeBillingIntegration.ts
> +
C'est un test la ligne blanche ? :-)

2021-02-15 14:13 UTC, ClaudeROSSI commented on src/integration/billing/stripe/StripeBillingIntegration.ts
> +
ooops ... removed ;)

2021-02-15 14:15 UTC, ClaudeROSSI commented on src/server/rest/CentralRestServerService.ts
> +          [ServerAction.BILLING_ATTACH_PAYMENT_METHOD]: BillingService.handleBillingAttachPaymentMethod.bind(this),
BillingRouter added ...
But I'm not sure to understand what happens if we have it twice (once in new RestFul API and still  declared the old way!)

2021-02-15 14:17 UTC, LucasBrazi06 commented on src/server/rest/CentralRestServerService.ts
> +          [ServerAction.BILLING_ATTACH_PAYMENT_METHOD]: BillingService.handleBillingAttachPaymentMethod.bind(this),
You can remove the old ones.
The old REST interface will be replaced by the new RESTful one.

2021-03-02 09:05 UTC, closed without merging

2021-03-02 09:06 UTC, ClaudeROSSI commented
Closing this one because a second branch will be used to provide the same coding after switching to the latest STRIPE API - version 8.*.*